### ISSUE TITLE
Invalid parameter(s): meta_data [rest_invalid_param]

### ISSUE THREAD

**Issue by willfaulds** [woocommerce/wc-api-dev#85]
Any attempts to update an order's **meta_data** fail.

This goes against the API documentation http://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties

WordPress 4.9.2
WooCommerce 3.2.6 
wc-api-php 2.0.0
Memory: 10 of 128 MB (8%) | WP LIMIT: 128 MB | PHP 7.1.12

**Outline of API call (PHP using wc-api-php 2.0.0):**
```
$woocommerce = new Client(
    'https://www....',
    '...',
    '...',
    [
        'wp_api' => true,
        'version' => 'wc/v2'
    ]
);

...create/load an wooOrder with $orderId

$data = [
  'id' => $orderId,
  'meta_data' => [ '_custom_field' => '24.54' ]
];

$woocommerce->put('orders/'.$orderId, $data);
```

**ERROR log**

```
[31-Jan-2018 09:49:53 Europe/London] PHP Fatal error:  Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Error: Invalid parameter(s): meta_data [rest_invalid_param] in /home/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:348
Stack trace:

#0 /home/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(378): Automattic\WooCommerce\HttpClient\HttpClient->lookForErrors(Object(stdClass))

#1 /home/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(414): Automattic\WooCommerce\HttpClient\HttpClient->processResponse()

#2 /home/vendor/automattic/woocommerce/src/WooCommerce/Client.php(69): Automattic\WooCommerce\HttpClient\HttpClient->request('orders/7712', 'PUT', Array)

#3 /home/woocommerce.php(95): Automattic\WooCommerce\Client->put('orders/7712', Array)

#4 /home/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 348

```

**Comment by willfaulds** [comment]
After discussing with WooCommerce support also logged here https://github.com/woocommerce/woocommerce/issues/18810

**Comment by mikejolley** [comment]
No need for duplicates. Responding in https://github.com/woocommerce/woocommerce/issues/18810 since this is a mistake on your side.
